name: Build

on:
  push:

env:
  LEIN_ROOT: true

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java-version: ["8", "11"]
        eval_in_leiningen: ["true", "false"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - name: run tests
        run: lein test
        env:
          eval_in_leiningen: ${{ matrix.eval_in_leiningen }}
